apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shopvac-pod-deletion-role
rules:
  - verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
      - watch
    apiGroups:
      - "*"
    resources:
      - pods
  - verbs:
      - watch
      - get
      - patch
      - delete
      - list